### ISSUE TITLE
Geo blocking

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#1]
UN-Sanction list, see how this is done by uniswap interface.

**Comment by adamazad** [comment]
How about just blocking IPs? Aave, Compound, and all DeFi protocols are behind Cloudflare. I think they're using this https://community.cloudflare.com/t/blocking-entire-countries/24172/12

**Comment by martinkrung** [comment]
I don't know how we can do this on ipfs! Some more research needed. How is omen dong this?

**Comment by adamazad** [comment]
@nicoelzer you are in charge of `mesa-ui.dev`, could you please look into geofencing in the Cloudflare IPFS bridge?

**Comment by nicoelzer** [comment]
@adamazad, mesa-ui.dev is only an internal staging domain, that won't be used to serve the actual product deployment. 

To make sure Mesa.eth will be untouchable, we should not rely on centralized providers such as Cloudflare. All DXdao products are hosted on IPFS and served on the ENS domain which can be governed by the DAO. As ENS domains don't allow to to setup geofence, we need to find a solution directly in the frontend.

**Comment by martinkrung** [comment]
@nicoelzer @adamazad

We need an external service for this.

We can ask an external API with the IP as input and then get a yes or no back. Once done, set a cookie with timout (30 days?) to not repeat on every request.

**Comment by adamazad** [comment]
I found https://github.com/ipfs/notes/issues/284 for anyone working on this issue.

[https://1change.exchange](1change.exchange)
[https://compound.finance](compound.finance)
[https://aave.com](aave.com)

They all use Cloudflare to block IPs.

> We can ask an external API with the IP as input and then get a yes or no back. Once done, set a cookie with timout (30 days?) to not repeat on every request.

Browsers can block cookies. This can be easily bypassed. Best to allow access Mesa on IPFS, but deny access on mesa.eth.link

**Comment by martinkrung** [comment]
Bypassing is not that an issue, it's easy with VPN anyway. It's just that you limit it and can say you have respected the UN List.
