### ISSUE TITLE
Create Mock data for bids.

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-interface#10]
A `Bid` type (or struct) has these properties

```typescript
interface Bid {
  price: number
  amount: number
  bidder: address
}
```

**Comment by martinkrung** [comment]
Best would be to generate bids randomly in the front-end over time. But the random needs to be tailored. I can help with this if I have if I get a start in JS. I think this would also visually nice to see in action on the chart and at this stage is worth to have something flashy.
