### ISSUE TITLE
Finding a decent JS library for charting

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#12]
https://www.amcharts.com/download/   (used by mesa.eth right now)
What about this: https://github.com/airbnb/visx, used here https://analytics.sushiswap.fi/bar
https://nivo.rocks, supercharged React dataviz components, built on top of d3js!

**Comment by adamazad** [comment]
I am experimenting with [chart.js](https://www.chartjs.org/)

**Comment by aabot123** [comment]
If would like another option - bit more work to implement, but a versatile React vizkit - [VictoryChart](https://formidable.com/open-source/victory/)

**Comment by chainlito** [comment]
I have worked with [Victory chart](https://formidable.com/open-source/victory/) before and it was good. Also works well with React than Chart.js. What do you think?
