### ISSUE TITLE
Implement a structure for i18n files

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-interface#13]
Translations are stored `/locales/<language-code>/translations.json`. I welcome suggestions on the best way to approach this.

**Comment by martinkrung** [comment]
Thats the code uniswap is using to load i18n: 

Uniswap usese https://www.i18next.com/ for this:

https://github.com/Uniswap/uniswap-interface/blob/master/src/i18n.ts
Language file ending up here
https://github.com/Uniswap/uniswap-interface/tree/master/public/locales

**Comment by martinkrung** [comment]
Thats the code uniswap is using to load i18n: 

Uniswap usese https://www.i18next.com/ for this:

https://github.com/Uniswap/uniswap-interface/blob/master/src/i18n.ts
Language file ending up here
https://github.com/Uniswap/uniswap-interface/tree/master/public/locales

**Comment by martinkrung** [comment]
Thats the code uniswap is using to load i18n: 

Uniswap usese https://www.i18next.com/ for this:

https://github.com/Uniswap/uniswap-interface/blob/master/src/i18n.ts
Language file ending up here
https://github.com/Uniswap/uniswap-interface/tree/master/public/locales
