### ISSUE TITLE
Remove `fixed` from sales URL

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-interface#155]
`sales/fixed/<sale-address>` is a bad implementation. It adds more complexity to the routing table.

## Detailed Description

It implies that each sale must be prefixed with its sale mechanism. Yet, the FairSale view does not have `fair` in it. All sale addresses should be `/sales/<sale-address>` regardless of the sale mechanism. 

## Possible Implementation

 - `SaleView`: fetch the sale type from subgraph/redux, then pass `saleId` to appropirate view 
   -  `FairSaleView`
   - `FixedPriceSaleView`

**Comment by adamazad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove fixed from sales URL](https://trello.com/c/9ki9Du3Z/143-remove-fixed-from-sales-url)

**Comment by martinkrung** [comment]
I think this is done, if you write " close #22" on your commit message a ticket will auto close..
