### ISSUE TITLE
Add "Approve" in the UX and functionality

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#156]
Sale investors need to approve token to be used by the sale contract. Design has to be defined, but best make a functional button somewhere and then we design later.

## Detailed Description

Did see this on gnosis-auction right now, its so standard, we never have been thinking of this:

![Screenshot at 2021-05-11 15-56-33](https://user-images.githubusercontent.com/918180/117827732-89ed2200-b271-11eb-82f7-866c192ea3b4.png)

![Screenshot at 2021-05-11 15-25-09](https://user-images.githubusercontent.com/918180/117827251-1ba85f80-b271-11eb-84be-2f6ac033f0bb.png)

**Comment by hhamud** [comment]
So Users must approve the smart contract for each and every new token before being allowed to bid at all?. If this is the case, I can create a quick figma sketch, before coding up the button.

**Comment by adamazad** [comment]
For sale investors, they have to approve the bidding tokens: USDC, DAI, or whatever sale creators choose. For sale creators, they have to approve the sale token.
