### ISSUE TITLE
Replace NotFound page with 404 Error Page

### ISSUE THREAD

**Issue by hhamud** [cryptonative-ch/mesa-interface#158]
## Detailed Description
* Replace NotFound page with 404 Error Page

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by martinkrung** [comment]
You know that Bertie made a design for the 404 as his last work for us? Look at the figma..
