### ISSUE TITLE
allocationMin is showed as "1" if 1000000000000000000 or 1 on smart contract level.  1000000000000000000 is right

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#160]
allocationMin is showed as "1" if 1000000000000000000 or 1 on smart contract level.  (1000000000000000000 is right)

## Description

Look at "Min" on frontend and the allocationMin in the editor/graphquery

## Expected Behavior

show the real number if BigNumber.from(1) is used, so ~0.0000000000000001

shows 0.0000000000000001

## Actual Behavior

![Screenshot at 2021-05-13 17-41-48](https://user-images.githubusercontent.com/918180/118151119-914c3100-b413-11eb-8301-8e4948ee4c04.png)
![Screenshot at 2021-05-13 17-41-32](https://user-images.githubusercontent.com/918180/118151122-927d5e00-b413-11eb-8767-465db71a6b19.png)
![Screenshot at 2021-05-13 17-36-29](https://user-images.githubusercontent.com/918180/118151126-9315f480-b413-11eb-9b88-decec92a94fd.png)
![Screenshot at 2021-05-13 17-37-40](https://user-images.githubusercontent.com/918180/118151125-927d5e00-b413-11eb-9012-587e79a7ed5a.png)

**Comment by hhamud** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [allocationMin is showed as "1" if 1000000000000000000 or 1 on smart contract level. 1000000000000000000 is right](https://trello.com/c/lNlo8rv7/148-allocationmin-is-showed-as-1-if-1000000000000000000-or-1-on-smart-contract-level-1000000000000000000-is-right)

**Comment by hhamud** [comment]
During the subgraph development, I just made the assumption that all the values would be in BigDecimal format therefore if `allocationMin` was 1 that would represent 1x10^(+decimal) rather than just 1x10^(-decimal). All the queries that use BigInt can be changed on the frontend to use `BigNumber.from` to convert it from a string into a the correct format.
