### ISSUE TITLE
Show Status of Network or Network (xdai/testnet)

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#162]
User should see to which network they are connected (xdai/rinkeby)

If a network is used where Mesa is not on, then a massage should be shown like

"Mesa is not present on mainnet/matic", pleas connect to xdai or rinkeby

## Context

User should understand why they can't connect. (Mainnet)

## Possible Implementation

Look like swapr is doing this! Or try to leverage existing solutions?

**Comment by mprasanjith** [comment]
I worked on a simple network switch / wallet disconnection panel.

![Network Switcher](https://user-images.githubusercontent.com/25136207/125443738-57bcac28-5579-4c03-a948-345e41d9b662.png)

![image](https://user-images.githubusercontent.com/25136207/125444024-b1b7d435-186b-48dd-98c9-e27652604075.png)


I already have the code written for the functionality of this. Just need to finalize the design now. If we're okay with this design I can go ahead and build this.
