### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-interface#17]
- React components
- Mesa utils `src/mesa/utils`
  - `isAuctionOpen`
  - `isAuctionUpcoming`
  - `isAuctionClosed`
  - `filterAuctionBidsByAddress`

**Comment by hhamud** [comment]
I'll start writing tests after I create each component. Right now I can't see any tests on the main branch, do you have any good libraries in mind for testing?. I don't want to use a different testing suite that you will be using soon.

**Comment by adamazad** [comment]
[Jest](https://jestjs.io] and [Test Library](https://testing-library.com/) are already installed. Unit tests for Components should be placed in the same folder named `<ComponentName>.spec.ts`

**Comment by adamazad** [comment]
Please start writing tests for Components.
