### ISSUE TITLE
Add separate container for `FixedPriceSale` `purchases` 

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-interface#175]
A container should accept a `saleId` and fetch the purchases independently using a GraphQL query. The hook is already there, should be easy to implement in a PR after 2dd4d5cf8547b07ac424741084f1088c0cd333f6 is merged

**Comment by hhamud** [comment]
Doesn't the frontend already do this?. I will need more details on what the exact problem is.

**Comment by hhamud** [comment]
Check if subgraph aggregates bids.

**Comment by martinkrung** [comment]
We talk about this:

![Screenshot at 2021-06-07 16-15-28.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/0f84301b-b62a-4e32-83fa-f84378acef85)
