### ISSUE TITLE
Implement sale progress bar for fixed price

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#208]
We had this at some point, as a mock,  but not connected to any real data

![Screenshot at 2021-06-08 11-33-03.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/00441638-c925-44db-a71a-2a5d8add6b9f)

* progress bar must also be visible on upcoming and finished sales.

**Comment by hhamud** [comment]
[Once I fix](#209 ) [the purchase list](#175 ), this should pop up along with it. In the code base, the progress bar is hidden and only appears if there are bids available in the cache or redux store.

**Comment by martinkrung** [comment]
If the logic is as described, then the first person to make a purchase does not see the progress bar. But there is crucial information on the progress bar which the first person needs to see.
