### ISSUE TITLE
RCP Error if above Max Allocation

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#214]
Max Allocation is 2. If somebody uses 5 in the form, an RCP error happens.  A warning massage is needed. I don't know if we have a general modal for warnings/error massage

![Screenshot at 2021-06-08 17-30-23](https://user-images.githubusercontent.com/918180/121217734-6a521500-c882-11eb-9db7-455ae5b4c13e.png)

**Comment by pimato** [comment]
Hey guys, just tried to bid on the new auction here and it does not seem to work:

https://user-images.githubusercontent.com/5337809/121216863-928d4400-c881-11eb-8d21-f2a3e081507b.mov
