### ISSUE TITLE
Fix sale input form

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/mesa-interface#218]
A few issues with the current sale input form

- Cursor can not be seen currently (seems like overkill CSS for simple input box)
- Decimals currently cause a fatal error and should not

**Comment by martinkrung** [comment]
See also #214, which is another issue

**Comment by rossneilson** [comment]
> I also think it should be the way that you choose how much WXDAI you are going to invest and then calculate the token you get. FPST should replace by the invested token (WXDAI)
> 
> Now it looks like this:
> 
> ![Screenshot at 2021-06-08 21-35-05.png](https://camo.githubusercontent.com/184484c291994b5d2180e8a7daca3ee6851d6acf2623896bca3d64355d1637fa/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630623462313636373463643333633663376334393532632f30376532623438342d626365382d346238352d396333362d363463656138343336643930)
> 
> See also #214, which is another related issue

I'll fix #214 with this and will make a separate issue for the ability to specify amount of WXDAI to invest
