### ISSUE TITLE
Implement ability to specify WXDAI to invest

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/mesa-interface#220]
There should be an input that allows amount of WXDAI to invest to be entered instead of output token.

Similar to how exchanges (sushi/uni) allow users to choose the amount of tokens of either input/output.

![2021-06-08 21.07.22.png](https://images.zenhubusercontent.com/60b4ff93c021492a4067ae98/b841e4b0-8538-47cb-9884-0fb14453a3a7)

**Comment by martinkrung** [comment]
I think people should only give in the amount they want to invest and then calculate in real time how much they get. Figma Design shows this perfect:

![Screenshot at 2021-06-10 18-11-50.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/3ba7137f-b158-4570-86b9-95e89b3d224e)

**Comment by rossneilson** [comment]
Sure, so there should be no way to specify the number of tokens to buy only the cost in WXDAI?
