### ISSUE TITLE
deposit an example json to IPFS

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#236]

**Comment by mprasanjith** [comment]
The mock JSON is available on IPFS as QmRVKi23YQmXLStgSK5bQS9QyiAeWZmjVNQTbx61NUAhcg.

Access through official gateway: https://ipfs.io/ipfs/QmRVKi23YQmXLStgSK5bQS9QyiAeWZmjVNQTbx61NUAhcg
