### ISSUE TITLE
Fix Withdraw Buttons on FixedPriceSale 

### ISSUE THREAD

**Issue by hhamud** [cryptonative-ch/mesa-interface#249]
## Description
* Fix Withdraw Buttons on FixedPriceSale 
![image.png](https://images.zenhubusercontent.com/60b7720fc41685a0d782c37a/2610a112-fe8f-4fab-9e31-592cbf93cb85)

## Expected Behavior
It should be smaller and be dynamic, switching from withdraw bid and claim bid depending on the threshold of the sale

## Steps to Reproduce

1.
2.
3.
4.

**Comment by martinkrung** [comment]
I think we should kill this design with a extra menu for the fixe price and make buttons. I did a draft for this in #175, scroll down..
