### ISSUE TITLE
Fractional amounts for Token purchases not appearing

### ISSUE THREAD

**Issue by hhamud** [cryptonative-ch/mesa-interface#254]
## Description

The decimal components for tokens that have been purchased are being rounded up or down.

## Expected Behavior
The decimal component should be shown up to 2 decimal places. 

## Actual Behavior
The number is being rounded to the nearest whole number. 

## Possible Fix
most likely just use the numeral library to prevent rounding

**Comment by martinkrung** [comment]
Should show 2.4 FPST
![Screenshot at 2021-06-14 17-25-51.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/fc500b1b-6fff-4cfa-b733-05c6e766b951)
