### ISSUE TITLE
Tooltip as help

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#264]
![Screenshot at 2021-06-16 17-55-05.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/ca8ba65e-6aa7-41c3-a712-4632015087f1)

from https://gnosis-auction.eth.link/

![Screenshot at 2021-06-17 09-22-13.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/d427e03f-144f-4a73-8192-0101d16d0c41)

Please add a design to the figma first

**Comment by mprasanjith** [comment]
I worked on a design for the popup and tooltip [here](https://www.figma.com/proto/h6oU7aqg0iTskSeWRYsaCj/Mesa-MVP-(Copy)?node-id=2101%3A7486&scaling=min-zoom&page-id=408%3A170). (Hover next to the the Min. allocation text in the Sale progress bar) 

@martinkrung Let me know what you feel about this.

**Comment by martinkrung** [comment]
Nice, this is perfect. 

- Please move this to the file I just gave you access to
- Please implement on 2 different places, one where you did the design and one where you think we need more information.
