### ISSUE TITLE
Integrate web3modal

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#275]
First only use Metamask

**Comment by martinkrung** [comment]
![Screenshot at 2021-06-18 15-37-30.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/2adce4d3-eaba-4dad-9bb6-0242891dbfad)

https://github.com/web3modal/web3modal

Project using this:

https://web3modal.com
https://defi.instadapp.io

**Comment by rossneilson** [comment]
I dont know what is causing this but currently, when you refresh the page the wallet doesn't reconnect.
If its simple or related it might be worth fixing this here

**Comment by mprasanjith** [comment]
Yeah, I don't think we have implemented functionality to connect automatically to the injected provider. I'm currently refactoring the current code for connecting to wallets. I'll implement that while I do these changes.

On an aside, there are certain things in the code-base that I feel is unorganized / more complicated than it should really be. We should do some refactoring if we find enough time.

**Comment by rossneilson** [comment]
Definitely!
If its small and related include it in here, but if its larger and potentially more complex then just make a new issue for it
