### ISSUE TITLE
Tools for easy feedback

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#281]

**Comment by martinkrung** [comment]
1. Link to github issues

https://github.com/cryptonative-ch/mesa-subgraph/issues/new

2. Link to a general google from

Can look very standard, please make an adapted design in figma first, then implement.

![Screenshot at 2021-06-22 11-04-04.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/180a8a77-6b45-44dd-99ef-23f8e924d740)

![Screenshot at 2021-06-22 11-09-45.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/514836cd-18a8-4ccd-9bca-4c136bcb960e)

**Comment by mprasanjith** [comment]
@martinkrung I did a draft design for the feedback component on Figma [here](https://www.figma.com/file/GmPzNigQwzGyL4jRBvXBiQ/Aqua-MVP?node-id=48%3A718). Hope you can have a look.

**Comment by martinkrung** [comment]
Very Nice!
