### ISSUE TITLE
Min and Max. Allocation in FE wrong or change in smartcontract?

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#285]
As amount has to be in the invested token/tokenIn, the compare for Min/Max Allocation has also be in tokenIn, not tokenOut

https://github.com/cryptonative-ch/mesa-smartcontracts/blob/48627ca58b39b541b1aa0bac6bc23bfbf6bcbdf5/contracts/sales/FixedPriceSale.sol#L141

![Screenshot at 2021-06-23 09-38-52.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/b28d3d1f-a5f2-4b69-8af7-e5521c485a0b)

In the UI Now

![Screenshot at 2021-06-23 09-37-42.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/45132644-c8dc-45bf-a21b-733a5da51619)

One possible solution, which I find confusing:

![Screenshot at 2021-06-23 09-44-22.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/4e64509d-4df1-4537-8f98-7c1d85353ee3)

Just calculate the values from max/min, but then the info on the smart contract and interface differ. This is confusing and makes the code more difficult to understand:

![Screenshot at 2021-06-23 09-48-10.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/84c6a18d-4c7c-4499-bb21-e9a2f8a66f55)

code which has been used start this sale:

![Screenshot at 2021-06-23 09-48-57.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/96d624be-6c9f-4025-9ed7-e3e0d5e5abde)

**Comment by rossneilson** [comment]
This is what I meant when I said changing everything to use tokenIn will involve changing everything in the UI currently.

**Comment by sacshin** [comment]
From an investor's point of view it makes sense to show the 'token in' on the front end, so people don't have to do mental gymnastics. If one buys a new coin, they know how much they want to invest, and don't really care about the outcome result. The one that shows the conversion rate, min/max 'token in' allocation, and lets you enter 'token in' amount, with a calculated result beneath is best.
