### ISSUE TITLE
Change all SC interactions to use tokenIn

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/mesa-interface#290]

**Comment by rossneilson** [comment]
After lots of discussion and confusion relating to what SC parameters and variables should/are denominated in we have a decided solution.
Currently the UI acts as if everything/most things are in tokenOut.
However now everything including max min allocation, min raise, buy amount, etc should use tokenIn.
The conversion should only ever happen in the SC when claiming tokens.

Changes also needed in SC and subgraph.

Perhaps avoid merging until SC are ready.

**Comment by martinkrung** [comment]
We wait until SC is ready, or changes there are cleare

**Comment by rossneilson** [comment]
I will likely make a start on this and keep it in a separate branch until SC are ready
