### ISSUE TITLE
Clicking on Approve while token purchase amount is entered results in fake error

### ISSUE THREAD

**Issue by mprasanjith** [cryptonative-ch/mesa-interface#297]
## Description

When approving a new token purchase, if an amount is entered in the input box, additional error alerts are shown, even when nothing has gone wrong.

## Expected Behavior

The token approval should pop-up on Metamask, without any additional alerts.

## Actual Behavior

The approval window shows up on Metamask, but the app also shows additional errors.

![image](https://user-images.githubusercontent.com/25136207/123509110-4cade980-d691-11eb-8e5f-a35d272aaa9c.png)

## Possible Fix

It looks like the purchase function also seems to be getting called, when the approve button is clicked.

## Steps to Reproduce

1. Enter a token purchase amount in the input box.
2. Click on the Approve button.
3. Error toast notifications will show up.

**Comment by rossneilson** [comment]
I am not able to reproduce this exact issue in dev. But it does trigger the buy confirmation popup which suggests it is triggering the buy action like Madusha says. Should be an easy fix.
