### ISSUE TITLE
Show amount sold on closed sale summary cards

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/mesa-interface#317]
Currently closed sale summary cards in /views/sales shows amount for sale and current price.
This would be more useful as amount sold and current price to just price.
Also some indication of a failed sale would also be useful. Maybe for now just highlighting the amount sold value in red like on the actual sale page.

![2021-07-04 12.13.22.png](https://images.zenhubusercontent.com/60b4ff93c021492a4067ae98/1adef8cd-4eea-43bf-87a1-0c6e92adeeb4)

**Comment by hhamud** [comment]
The [figma designs](https://www.figma.com/file/7vH0nZB72tizFbhT7gtizo/Mesa-MVP?node-id=408%3A170) will aid you well here.  

![image.png](https://images.zenhubusercontent.com/60b7720fc41685a0d782c37a/41b16c32-4960-47b2-b253-338d7e58557c)
