### ISSUE TITLE
Fix develop preview in netlify

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/mesa-interface#338]
https://aqua-test.dxdao.net/

Still seems to be using old subgraph api
Needs updating to new version
Not sure if previous change didn't go through or needs updated somewhere else

REACT_APP_SUBGRAPH_ENDPOINT=https://api.thegraph.com/subgraphs/name/adamazad/aqua-xdai-dev

**Comment by hhamud** [comment]
I cannot fix this as this is an issue within netlify. I have also tried to switch over to using GH pages but I do not have the necessary access to github credentials for account hosting the projects. [comment here](https://app.zenhub.com/workspaces/aqua-60b4b1903fe23d001b107ae2/issues/cryptonative-ch/mesa-interface/326#issuecomment-881610942)
