### ISSUE TITLE
Bid list not updating on new purchase

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/mesa-interface#356]
When a purchase is placed on the fixed price sale it shows a success notification however the bidlist is not updated until refresh. On first purchase there is an error that appears. After there is no error in the console so something likely is just broken with the redux action dispatching

**Comment by rossneilson** [comment]
![](https://user-images.githubusercontent.com/25136207/127216017-c40e7bdb-5553-44c4-9d31-341b01038420.png)

**Comment by hhamud** [comment]
Solved in this PR #388
