### ISSUE TITLE
Deploy Aqua to Rinkeby

### ISSUE THREAD

**Issue by mprasanjith** [cryptonative-ch/mesa-interface#369]

**Comment by adamazad** [comment]
This should be closed.

**Comment by mprasanjith** [comment]
I actually kept this open because we were having some issues with the subgraph. Will close this once that's sorted.

**Comment by adamazad** [comment]
What was the deployment for Rinkeby's subgraph, please?

**Comment by mprasanjith** [comment]
It's https://thegraph.com/legacy-explorer/subgraph/mprasanjith/aqua-rinkeby-next

**Comment by mprasanjith** [comment]
The transaction that breaks the subgraph seems to be [this](https://rinkeby.etherscan.io/tx/0x71961c514c1e67b829bdc5d8c975473b76d6034636fc75fc106f484da8282ee9). Couldn't dig in to this yet. Will you be able to have a look?

**Comment by adamazad** [comment]
Gladly, I will update this thread :)

**Comment by rossneilson** [comment]
Deploying sales to rinkeby now works the same as xdai!
