### ISSUE TITLE
Routing issue in gh-pages

### ISSUE THREAD

**Issue by hhamud** [cryptonative-ch/mesa-interface#370]

**Comment by hhamud** [comment]
Direct links to any sale gives a specific gh page 404 error.

**Comment by mprasanjith** [comment]
This is a common issue with Github pages and SPA routing. Have a look at [this](https://github.com/rafgraph/spa-github-pages) or [this](https://www.freecodecamp.org/news/deploy-a-react-app-to-github-pages/) for potential solutions.
