### ISSUE TITLE
Make auction bids more realistic

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-interface#38]
Currently, the auction data is being randomly generated in `src/data/auction.ts` adhering to this:

```typescript
export interface AuctionBid {
  sellAmount: BigNumber // Number of tokens the investor wants to buy
  buyAmount: BigNumber // Price at which they wish to buy
  address: string // Their Ethereum address
}
```

In [`Simulation` view](../src/views/Simulation/index.tsx), a random bid is added every two second using

```
addBid({
  address: getRandomWallet().address,
  sellAmount: BigNumber.from(getRandomInteger(1, 30)), // DAI
  buyAmount: BigNumber.from(getRandomInteger(1, 300)), // SIM/ERC20
})
```

Notice that the data is bound between [1,30] and [1,300] that does not reflect actual data points for a real-world auction. There are ways to solve this, but the demo/simulation data should be more realistic. Ideas are welcome.

**Comment by martinkrung** [comment]
To do it more realistic we need to call addBid with around 50 bids  at the start or have a static data. We imagine a fair value for SIM to be around 200. So if you bid above this you are in the sale, if below you may be out. I expect to be a lot of bids around 200 then. Gamblers will be near of 200, people who want to be sure to be in will be set higher

```
addBid({
  address: getRandomWallet().address,
  sellAmount: 20, // DAI
  buyAmount: 204, // SIM/ERC20
})
```

**Comment by hhamud** [comment]
As I am re-writing the cancel button #79 , I've realised that I need to change the way the data is generated on the front-end. Currently it is only generated within the demo/simulation page. I've thought about just using the context library to make it easier for the components to edit the bid array but I also need to generate an initial set of random bids. 

Any ideas will be welcome.

**Comment by adamazad** [comment]
You can use the Redux store. Create actions for each event and a reducer. Here's a sample https://github.com/adamazad/trador-web/blob/v2/src/screens/Messages/redux/index.ts

**Comment by martinkrung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [w](https://trello.com/c/ldIahYzm/19-w)
