### ISSUE TITLE
The virtual settelment price should be calculated and updated on every bid

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#39]
At the  top of the window xxx SIM/DAI is shown, but price is not changing on ever bid made by hand or per random. 

So is virtual settelment price called ever bid?
If yes, it must be a front-end issue.

Also we may label it to Virtual Settelment Price  xxx SIM/DAI 

See also this #14

**Comment by hhamud** [comment]
The virtual price does update on every bid based upon tionthe easy auction clearing price func
