### ISSUE TITLE
Add new token to wallet button

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/mesa-interface#405]
A suggestion from Nathan, we should have a button in the UI to add new tokens being sold to the user's wallet.
I can imagine once we launch we could get lots of support requests from new users who dont understand how to add new tokens to their wallet.
We already have the tokenOut address displayed in the UI so I think it makes sense to maybe add a + icon by that link to the block explorer.
The button could also be used in the claim list once the user has claimed their tokens. 

https://docs.metamask.io/guide/registering-your-token.html
(Not sure what this will look like for walletconnect)

**Comment by mprasanjith** [comment]
WalletConnect support doesn't seem to exist for this.

In my experience with Trust Wallet, it usually automatically discovers new tokens and lists them without any manual interaction, unlike MetaMask. I'm not sure if this is the case with other wallets though.

For now I'll implement this conditionally, and only show the + button if the user is using MetaMask.

**Comment by rossneilson** [comment]
This seems like a good solution
