### ISSUE TITLE
Claim Token Failure Transactions

### ISSUE THREAD

**Issue by hhamud** [cryptonative-ch/mesa-interface#415]
@mprasanjith This is just a generic message that is shown when a purchase has any sort of error, so it seems that Metamask classifies rejecting a transaction request as an error. I am not sure how other wallets handle rejecting a transaction request. So what would be the best way of handling this?.

1. If all the other wallets handle it the same way as Metamask does, I could just create an exception for that specific error message and reset the card's state on transaction rejects. 
2. Any suggestions would be welcome.

_Originally posted by @hhamud in https://github.com/cryptonative-ch/mesa-interface/issues/385#issuecomment-893837789_

**Comment by mprasanjith** [comment]
@hhamud the standard in EIP-1193 is to reject the request with a [ProviderRpcError](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#rpc-errors) (code: 4001), and all wallet providers should adhere to it. I think we can handle this specific rejection.
