### ISSUE TITLE
Warn people if they set bid way to low

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#43]
If people set bid/tx more than 30% below virtual settlement price show a warning. This warning should not prevent the bid, but warn people that chances may be low to be included into the final sale. In a way the percentage should go lower to the end of the sale because the virtual settlement price will stabilize to the end of the sale. 

Rationale behind this:

It make no sens that people set this kind of bids on-chain, every bid on chain makes computation more expensive on settlement and people have to withdraw again.

Text could be:

**Your bid is $foo % below the current virtual settlement price. Chances that you will in the sale will be low. Just proceed if you know what you are doing.**

**Comment by hhamud** [comment]
#65 created a small popup window if the token price is set too low (at less than 70% of the settlement price when pressing the submit button)
