### ISSUE TITLE
Write Contribution guide / DevOps docs

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-interface#46]
- Code style guideline?
- #31 delete

**Comment by adamazad** [comment]
# Contribution Guideline

# Abstract

Mesa is an open-source project, including but not limited to the Front End interface and Solidity Smart Contracts. As such, a Contritubtion Guideline shall facilitate the foundation for a collaborative ground for every contributor working on Mesa codebase(s).

# Style

## Structure

At Mesa, we are using React to build the frontend. Our current code structure looks like

1. General Components
    1. Placed in `src/components`
    2. Each Component has its own directory and a `index.tsx` that exports the Component
2. Layouts in `src/layouts`
3. Hooks in `src/hooks`
4. Views in `src/views`
    1. Each view has a `index.tsx` 
    2. Components specific to view are placed in `src/views/<ViewName>/components`
5. Assets in `src/assets`
    1. SVG in `src/assets/svg`
    2. Images in `/src/assets/images`
6. Redux
    1. Store in `src/redux/store.ts`
    2. Ducks in `src/redux/<DuckName>.ts`
7. Styles in `src/styles`
    1. Theme in `sr

## No Default Export

Except for external modules, all internal files must avoid default exports in ES6.

**Good**

```jsx
// GoodExport.ts
export function GoodExport(){
	return "I am exported using export"
}

// index.ts
import { GoodExport } from './GoodExport.ts'
```

**Bad**

```jsx
// NoSoGoodExport.ts
export function NoSoGoodExport(){
	return "I am exported using export"
}

// index.ts
import VeryGoodExport from './NoSoGoodExport.ts'
```

As you can see, with the second example, the imported name can be dynamic. Please avoid this.

## Group Imports

Imports should be grouped by their categories:

1. External imports
    1. functions, objects, interfaces, classes
2. Interfaces: imports from `src/interfaces` 
3. Components
    1. Components in `src/components`
    2. View Components in `views/<ViewName>/components` 
4. Layouts: layouts defined in `src/layouts`
5. Hooks: React Hooks defined in `src/hooks`
6. Helper/Util functions

**Good**

```jsx
// Externals
import styled, { useTheme } from 'styled-components'
import { useTranslation } from 'react-i18next'
import { useDispatch } from 'react-redux'
import React, { useEffect } from 'react'
import numeral from 'numeral'

// Actions
import { setPageTitle } from 'src/redux/page'

// Components
import { Container } from 'src/components/Container'
import { CardBody } from 'src/components/CardBody'
import { Header } from './components/Header'
import { Card } from 'src/components/Card'
import { Flex } from 'src/components/Flex'

// Layouts
import { Center } from 'src/layouts/Center'

export function IndexView() {
  
  const dispatch = useDispatch()
  const [t] = useTranslation()
  const theme = useTheme()

  useEffect(() => {
    dispatch(setPageTitle(t('indexTitle')))
  }, [t, dispatch])

  return (
    <Center minHeight="100%">
      <Container>
        <Header title={auction.tokenName} />
        <Card mb={theme.space[4]}>
          <CardBody>
              Hello world
          </CardBody>
        </Card>
      </Container>
    </Center>
  )
}
```

## Code Indentation

We are using two spaces to intend code. Developers who use spaces get paid more.

# Tests

## Unit Tests

### Components

Components are unit tested. Unit tests are placed in `src/components/<ComponentName>/<ComponentName>.spec.ts`

**Comment by hhamud** [comment]
#64 I've created an issue templates and pull request templates folder for better structuring. I also see that you've been developing the contribution guidelines, I wrote a small introduction to that in that pull request. So can we merge the two together?

**Comment by martinkrung** [comment]
Move this to contribute.md or simmilar
