### ISSUE TITLE
Show a count-down timer on top

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#49]
Something similar like this. As we do the design completely new, don't spend too much on look and fell righ now:

![▶-Page-1-Wireframes](https://user-images.githubusercontent.com/918180/106741942-a8ad9e00-661c-11eb-992b-25ad4e2a8318.png)

**Comment by hhamud** [comment]
Created a basic timer component on the Github branch. I just need someone to take a quick look over it before merging to the main branch
