### ISSUE TITLE
Enhance readability of list

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#56]
* sort after dai price per token (it needs not to be sortable in the front-end, just do it with JS)
* All numbers should be right adjusted
* Price per token should be calculated $dai/mesa (New column)
* How much token the person gets should be calculated on virtual settlement price (VSP) (New column) 
* Use monospace font, add this to font.css @import url('https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap');
![Screenshot at 2021-02-04 14-51-34](https://user-images.githubusercontent.com/918180/106904917-082eab00-66fc-11eb-8933-624bfd02be34.png)
![Screenshot at 2021-02-04 14-49-51](https://user-images.githubusercontent.com/918180/106904919-08c74180-66fc-11eb-9a09-5b6f92db8069.png)

**Comment by adamazad** [comment]
This wait for Bertie's input as he's the UX/UI designer for Mesa.

**Comment by martinkrung** [comment]
This is important for me, its disturbing, I get eye cancer.
