### ISSUE TITLE
Disable Bidding When Auction Ends

### ISSUE THREAD

**Issue by hhamud** [cryptonative-ch/mesa-interface#57]
Currently nothing happens when the timer for the auction reaches 0. The auction bidding form should be disabled when the the auction ends and the timer reaches 0. The final settlement price and all the successful bids should be shown but I am not sure how to best simulate this as it would take some time in reality, so for now the bidding button should be disabled and graph should become static. 

Deciding on how to best simulate the allocation will be a separate issue from this one.

**Comment by adamazad** [comment]
Utilize `isAuctionClosed` to check if an auction is closed. Under the hood, it uses `startBlock` and `endBlock`. All timestamps from the smart contract are in UTC timezone.
