### ISSUE TITLE
Wallet connect

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#6]
Use omens code base for this?

https://github.com/protofire/omen-exchange

**Comment by adamazad** [comment]
I have written few hooks for my other projects. I can push them for now.

**Comment by 0xVenky** [comment]
Omen uses an old version of walletConnect. If Mesa chooses to reuse Omen's implementation , check if they are upgrading to a new version and then work on this. :)

**Comment by light-fury** [comment]
I used a different module called useWallet (https://github.com/aragon/use-wallet) for wallet connection for more convenient usage.
