### ISSUE TITLE
Implement Single Sales Page for Desktop

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#86]
Implement the Single Sales Page according to the Design from Bertie

## Context

Link to figma

## Possible Implementation

Usage of any framework?

**Comment by martinkrung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [d](https://trello.com/c/5V9TAOXk/18-d)

**Comment by light-fury** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Title Bar of the Token Sales Details Page](https://trello.com/c/Q3Hr6k73/29-implement-title-bar-of-the-token-sales-details-page)

**Comment by light-fury** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Current Status Card with Graph integration](https://trello.com/c/65nt971q/30-implement-current-status-card-with-graph-integration)

**Comment by light-fury** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement add new bid card](https://trello.com/c/yUmDyT8b/31-implement-add-new-bid-card)

**Comment by light-fury** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Bid List card](https://trello.com/c/aHRq220T/32-implement-bid-list-card)

**Comment by light-fury** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement auction closed card](https://trello.com/c/wG4FQESK/33-implement-auction-closed-card)

**Comment by light-fury** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement change bid form](https://trello.com/c/kGRCMafp/34-implement-change-bid-form)

**Comment by light-fury** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Tests to components](https://trello.com/c/nxxbQhsL/39-add-tests-to-components)
